/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sauvik.bhowmik.anik;

import java.awt.Color;

/**
 *
 * @author ANIK
 */
public class UpSchedule extends javax.swing.JFrame {

    /**
     * Creates new form UpSchedule
     */
    public UpSchedule() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(590, 625));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\JavaPrograms\\NetBeans_Projects\\BusSchedule\\bus2.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 280);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Siyam Rupali", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 153, 0));
        jTextField1.setText("৯ঃ০০ কলেজগেট - ঢাবি (বি আর টি সি - ৬১১৬)");
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(0, 500, 310, 30);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Siyam Rupali", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 0, 51));
        jTextField2.setText("৫ঃ৫৫ শিব্বাড়ি - ঢাবি ");
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(0, 290, 160, 30);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Siyam Rupali", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 153, 0));
        jTextField3.setText("৬ঃ২০ কলেজগেট - ঢাবি (বি আর টি সি - ০৭৫৫)");
        jTextField3.setBorder(null);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(0, 320, 310, 30);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Siyam Rupali", 1, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 0, 51));
        jTextField4.setText("৬ঃ৩০ শিব্বাড়ি - ঢাবি (বি আর টি সি - ৬০৫৭)");
        jTextField4.setBorder(null);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(0, 350, 310, 30);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Siyam Rupali", 1, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 153, 0));
        jTextField5.setText("৬ঃ৩৫ কলেজগেট - ঢাবি (বি আর টি সি - ৫৮১৭)");
        jTextField5.setBorder(null);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(0, 380, 310, 30);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Siyam Rupali", 1, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 0, 51));
        jTextField6.setText("৭ঃ০০ কলেজগেট - ঢাবি (বি আর টি সি - ৬২২১)");
        jTextField6.setBorder(null);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(0, 410, 310, 30);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Siyam Rupali", 1, 12)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(51, 153, 0));
        jTextField7.setText("৭ঃ১৫ কলেজগেট - ঢাবি (বি আর টি সি - ৬১২৪)");
        jTextField7.setBorder(null);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(0, 440, 310, 30);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Siyam Rupali", 1, 12)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 0, 51));
        jTextField8.setText("৭ঃ৩০ কলেজগেট - ঢাবি (বি আর টি সি - ৫০২০)");
        jTextField8.setBorder(null);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(0, 470, 310, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
