/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sauvik.bhowmik.anik;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ANIK
 */
public class Clock extends javax.swing.JFrame {

    /**
     * Creates new form Clock
     */
    
    int timeRun = 0;
    
    private ImageIcon icon;
    public Clock() {
        initComponents();
        
        /*The following code is to make a custom icon for the jFrame*/
        icon = new ImageIcon(getClass().getResource("image.jpg"));
        this.setIconImage(icon.getImage());
        
        new Thread(){
            
          public void run(){
              while(timeRun == 0){
              
                  Calendar cal = new GregorianCalendar();
                  
                  //DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy ");
                  //Calendar cal1 = Calendar.getInstance();
                  
                  String date = new Date().toString().substring(0, 10) ;
                  
                  int hour = cal.get(Calendar.HOUR);
                  int min = cal.get(Calendar.MINUTE);
                  int sec = cal.get(Calendar.SECOND);
                  int AM_PM = cal.get(Calendar.AM_PM);
                  
                  String day_night = "";
                  
                  if(AM_PM == 1){
                      day_night = "PM";
                  }
                  else{
                      day_night = "AM";
                  }
                  
                  String time = hour + ":" + min + ":" + sec + " " + day_night ;
                  
                  clockLabel.setText(time);
                  //dateLabel.setText(""+date);
              }
          }  
        }.start();
        
        
    }
    /*Following portion is being used to move the date from left to right*/   
    int x = 0, y = 150;
    public void paint(Graphics g){
        
        super.paint(g);
        Graphics2D g2 = (Graphics2D)g;
        Font font = new Font("Tahoma",Font.BOLD+Font.PLAIN,18);
        g2.setFont(font);
        g2.setColor(Color.red);
        
        String date = new Date().toString().substring(0, 10) ;
        g2.drawString(""+date, x, y);
        
        try {
            Thread.sleep(100);
            
        } catch (Exception ex) {
        }
        
        x+=5;
        if(x>this.getWidth()){
            x=0;
        }
        repaint();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clockLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(350, 150));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        clockLabel.setBackground(new java.awt.Color(102, 102, 102));
        clockLabel.setFont(new java.awt.Font("DS-Digital", 1, 48)); // NOI18N
        clockLabel.setForeground(new java.awt.Color(0, 51, 255));
        clockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(clockLabel);
        clockLabel.setBounds(30, 10, 350, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clockLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
