/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sauvik.bhowmik.anik.classroutine;

import java.awt.Color;
import java.awt.Container;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author ANIK
 */
public class ClassRoutine extends javax.swing.JFrame {
    
    
    /**
     * Creates new form ClassRoutine
     */
    public ClassRoutine() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }
   
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(1025, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Downloads\\iitlogo-blue.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 175, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Downloads\\4258_Institute_large.jpeg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(870, 20, 120, 140);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField1.setText("            8th Semester");
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(390, 60, 220, 30);

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField2.setText("                Class Routine 2016                              ");
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(410, 10, 380, 50);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField3.setText("     8.00AM");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(110, 170, 110, 40);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField4.setText("     3.00PM");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(880, 170, 110, 40);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField5.setText("     9.00AM");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(220, 170, 110, 40);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField6.setText("    10.00AM");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(330, 170, 110, 40);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField7.setText("    11.00AM");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(440, 170, 110, 40);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField8.setText("    12.00PM");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(550, 170, 110, 40);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 0, 0));
        jTextField9.setText("     1.00PM");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(660, 170, 110, 40);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField10.setText("      2.00PM");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(770, 170, 110, 40);

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 0, 0));
        jTextField11.setText("     FRI");
        getContentPane().add(jTextField11);
        jTextField11.setBounds(10, 450, 100, 40);

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(0, 0, 204));
        jTextField12.setText("      SAT");
        getContentPane().add(jTextField12);
        jTextField12.setBounds(10, 210, 100, 40);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(0, 0, 153));
        jTextField13.setText("     SUN");
        getContentPane().add(jTextField13);
        jTextField13.setBounds(10, 250, 100, 40);

        jTextField14.setEditable(false);
        jTextField14.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(0, 0, 204));
        jTextField14.setText("     MON");
        getContentPane().add(jTextField14);
        jTextField14.setBounds(10, 290, 100, 40);

        jTextField15.setEditable(false);
        jTextField15.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(51, 0, 204));
        jTextField15.setText("     TUE");
        getContentPane().add(jTextField15);
        jTextField15.setBounds(10, 330, 100, 40);

        jTextField16.setEditable(false);
        jTextField16.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(0, 0, 204));
        jTextField16.setText("     WED");
        getContentPane().add(jTextField16);
        jTextField16.setBounds(10, 370, 100, 40);

        jTextField17.setEditable(false);
        jTextField17.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(0, 0, 204));
        jTextField17.setText("     THU");
        getContentPane().add(jTextField17);
        jTextField17.setBounds(10, 410, 100, 40);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setText("SE 801");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(770, 370, 220, 40);

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton2.setText("CSE 802");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 410, 220, 40);

        jButton3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton3.setText("SE 803");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 210, 220, 40);

        jButton4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton4.setText("OPT 1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(440, 410, 220, 40);

        jButton5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton5.setText("SE 801");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(220, 290, 220, 40);

        jButton6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton6.setText("SE 801");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(220, 330, 220, 40);

        jButton7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton7.setText("CSE 802");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(110, 370, 220, 40);

        jButton8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton8.setText("SE 801");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(220, 250, 220, 40);

        jButton9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton9.setText("OPT 2");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(440, 250, 220, 40);

        jButton10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton10.setText("OPT 3");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(440, 290, 220, 40);

        jButton11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton11.setText("OPT 2");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(440, 330, 220, 40);

        jButton12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton12.setText("OPT 3");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(440, 370, 220, 40);

        jButton13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton13.setText("SE 803");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(770, 210, 220, 40);

        jButton14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton14.setText("SE 801");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(770, 250, 220, 40);

        jButton15.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton15.setText("OPT 1");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(770, 290, 220, 40);

        jButton16.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton16.setText("SE 801");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(770, 330, 220, 40);

        jButton17.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 0, 0));
        jButton17.setText("LUNCH");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(660, 210, 110, 240);
        getContentPane().add(jButton18);
        jButton18.setBounds(880, 410, 110, 40);
        getContentPane().add(jButton19);
        jButton19.setBounds(110, 210, 110, 40);
        getContentPane().add(jButton20);
        jButton20.setBounds(220, 210, 110, 40);
        getContentPane().add(jButton21);
        jButton21.setBounds(330, 210, 110, 40);
        getContentPane().add(jButton22);
        jButton22.setBounds(110, 250, 110, 40);
        getContentPane().add(jButton23);
        jButton23.setBounds(110, 290, 110, 40);

        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24);
        jButton24.setBounds(110, 330, 110, 40);

        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25);
        jButton25.setBounds(330, 370, 110, 40);
        getContentPane().add(jButton26);
        jButton26.setBounds(330, 410, 110, 40);
        getContentPane().add(jButton27);
        jButton27.setBounds(770, 410, 110, 40);

        jButton28.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 0, 0));
        jButton28.setText("HOLIDAY");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28);
        jButton28.setBounds(110, 450, 880, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        /*close();
        ClassRoutine classroutine = new ClassRoutine();
        classroutine.setVisible(false);*/
        SE803 spm = new SE803();
        spm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        
        SE803 spm = new SE803();
        spm.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
        SE801 project = new SE801();
        project.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        SE801 project = new SE801();
        project.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        SE801 project = new SE801();
        project.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        
        SE801 project = new SE801();
        project.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        
        SE801 project = new SE801();
        project.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        SE801 project = new SE801();
        project.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        OPT2 scm = new OPT2();
        scm.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
        OPT2 scm = new OPT2();
        scm.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       
        OPT3 ml = new OPT3();
        ml.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
        OPT3 ml = new OPT3();
        ml.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        
        OPT1 image = new OPT1();
        image.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        OPT1 image = new OPT1();
        image.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        CSE802 data = new CSE802();
        data.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CSE802 data = new CSE802();
        data.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        /*close();
        ClassRoutine classroutine = new ClassRoutine();
        classroutine.setVisible(false);*/
        Holiday holiday = new Holiday();
        holiday.setVisible(true);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        /*close();
        ClassRoutine classroutine = new ClassRoutine();
        classroutine.setVisible(false);*/
        Lunch lunch = new Lunch();
        lunch.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassRoutine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassRoutine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassRoutine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassRoutine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ClassRoutine().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
