/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sauvik.bhowmik.anik.classroutine;

import java.awt.Color;

/**
 *
 * @author ANIK
 */
public class SE801 extends javax.swing.JFrame {

    /**
     * Creates new form SE801
     */
    public SE801() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField1.setText("                          SE 801 : Project");
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(32, 35, 430, 41);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField3.setText("6");
        jTextField3.setBorder(null);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(200, 350, 30, 35);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField4.setText("Mr. Rezvi Shahariar ");
        jTextField4.setBorder(null);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(200, 80, 146, 40);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField5.setText("Assistant Professor,");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(200, 120, 150, 30);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField6.setText("IIT, University Of Dhaka.");
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(200, 150, 180, 29);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField7.setText("Mr. Asif Imran");
        jTextField7.setBorder(null);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(200, 220, 146, 36);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField8.setText("Lecturer,");
        jTextField8.setBorder(null);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(200, 250, 190, 31);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField9.setText("IIT, University Of Dhaka.");
        jTextField9.setBorder(null);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(200, 280, 160, 29);

        jTextField10.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jTextField10.setText("&");
        jTextField10.setBorder(null);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(240, 190, 30, 30);

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jTextField11.setText("Course Teachers :");
        jTextField11.setBorder(null);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(32, 82, 163, 35);

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField12.setText("403");
        jTextField12.setBorder(null);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(200, 380, 163, 35);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jTextField13.setText("Credits :");
        jTextField13.setBorder(null);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(30, 320, 163, 35);

        jTextField14.setEditable(false);
        jTextField14.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField14.setText("6");
        jTextField14.setBorder(null);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(200, 320, 30, 35);

        jTextField15.setEditable(false);
        jTextField15.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jTextField15.setText("Total classes/week:");
        jTextField15.setBorder(null);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(30, 350, 163, 35);

        jTextField16.setEditable(false);
        jTextField16.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jTextField16.setText("LAB No. :");
        jTextField16.setBorder(null);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(30, 380, 163, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\ClassRoutine\\asif.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 230, 90, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\ClassRoutine\\rizvi.JPG")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 90, 90, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SE801.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SE801.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SE801.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SE801.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SE801().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
