/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sauvik.bhowmik.anik.classroutine;

import java.awt.Color;

/**
 *
 * @author ANIK
 */
public class SE803 extends javax.swing.JFrame {

    /**
     * Creates new form SE803
     */
    public SE803() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField1.setText("SE 803: Software Project Management");
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(60, 20, 340, 40);

        jTextField10.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jTextField10.setText("Course Teacher:");
        jTextField10.setBorder(null);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(20, 90, 150, 30);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField6.setText("Mr. Ajmal Huda");
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(190, 90, 110, 30);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField5.setText("CTO,");
        jTextField5.setBorder(null);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(190, 120, 70, 30);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField3.setText("bKash Limited.");
        jTextField3.setBorder(null);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(190, 150, 120, 30);

        jTextField12.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jTextField12.setText("Credits:");
        jTextField12.setBorder(null);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(20, 210, 100, 30);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField13.setText("3");
        jTextField13.setBorder(null);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(190, 210, 30, 30);

        jTextField2.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jTextField2.setText("Total classes/week:");
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(20, 260, 170, 30);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField9.setText("1");
        jTextField9.setBorder(null);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(190, 260, 30, 30);

        jTextField16.setEditable(false);
        jTextField16.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jTextField16.setText("LAB No. :");
        jTextField16.setBorder(null);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(20, 300, 130, 35);

        jTextField14.setEditable(false);
        jTextField14.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField14.setText("403");
        jTextField14.setBorder(null);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(190, 300, 30, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\ClassRoutine\\ajmal.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 90, 100, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SE803.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SE803.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SE803.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SE803.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SE803().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
