/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sauvik.bhowmik.anik;

import java.awt.Color;

/**
 *
 * @author ANIK
 */
public class Nobomi extends javax.swing.JFrame {

    /**
     * Creates new form Nobomi
     */
    public Nobomi() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(625, 525));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 0, 120, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 120, 120, 120);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 0, 120, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 0, 120, 120);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 0, 120, 120);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 0, 120, 120);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 120, 120);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 120, 120, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 240, 120, 120);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 360, 120, 120);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(100, 360, 120, 120);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(200, 360, 120, 120);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 360, 120, 120);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(400, 360, 120, 120);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(500, 360, 120, 120);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(500, 240, 120, 120);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Siyam Rupali", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("২৩ আশ্বিন(ভাঃ ১৮ আশ্বিন), ১০ অক্টোবর, সোমবার-সুঃ উঃ \n৫।৩৫, অঃ ৫।১৪। পূর্বাহ্ণ ৯।২৮। মহানবমী রাত্রি ৫।৫১ পর্যন্ত ।\n শ্রীশ্রীদুর্গাষষ্ঠী । পূর্বাহ্ণ মধ্যে (কিন্তু বারবেলানুরাধে দিবা ৮।৩০\n মধ্যে) শ্রীশ্রীশারদীয়া দুর্গাদেবীর ষষ্ঠাদিকল্পারম্ভ ও ষষ্ঠীবিহিত \nপূজা প্রশস্তা (অত্রকৃত্যে কারবেলানুরোধে দিবা ৭।২ মধ্যে পুনঃ\n দিবা ৮।৩০ গতে পূর্বাহ্ণ মধ্যে) শ্রীশ্রীশারদীয়া দুর্গাদেবীর \nমহানবম্যাদিকল্পারম্ভ ও মহানবমীবিহিত পূজা প্রশস্তা(অত্রকৃত্যে \nকারবেলানুরোধে নিরবকাশে ন’ বহু সম্মতঃ)। পূর্বাহ্ণ মধ্যে বীরাষ্টমীব্রত \nও মহাষ্টমী ব্রতের পারণ।");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 120, 410, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nobomi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nobomi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nobomi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nobomi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Nobomi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
