/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sauvik.bhowmik.anik;

import java.awt.Color;

/**
 *
 * @author ANIK
 */
public class Saptami extends javax.swing.JFrame {

    /**
     * Creates new form Saptami
     */
    public Saptami() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(625, 535));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 390, 120, 120);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 260, 120, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 130, 120, 120);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 120, 120);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 0, 120, 120);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 0, 120, 120);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 0, 120, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, 0, 120, 120);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(500, 0, 120, 120);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(500, 130, 120, 120);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Siyam Rupali", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("২১ আশ্বিন(ভাঃ ১৬ আশ্বিন), ৮ অক্টোবর, শনিবার-সুঃ উঃ \n৫।৩৪, অঃ ৫।১৬। পূর্বাহ্ণ ৯।২৮। সপ্তমী অপরাহ্ণ ৪।৪৬ পর্যন্ত ।\n শ্রীশ্রীশারদীয়া দুর্গাপূজা। পূর্বাহ্ণমধ্যে দ্ব্যাত্মকচরলগ্নে ও চরণবাংশে\n (কিন্তু কালবেলানুরোধে দিবা ৭।২ গতে পূর্বাহ্ণ মধ্যে) \nশ্রীশ্রীশারদীয়া দুর্গাদেবীর নবপত্রিকা প্রবেশ, স্থাপন, সপ্তম্যাদি \nকল্পারম্ভ ও সপ্তমীবিহিত পুজা। প্রশস্তা(অত্রকৃত্যে কারবেলানুরোধে\n নিরবকাশে ন’ বহু সম্মতঃ)। দেবীর ঘোটকে আগমন।\n ফল-ছত্রভংগ। রাত্রি ১১।১ গতে ১১।৪৯ মধ্যে দেবীর \nঅদ্ধরাত্রবিহিত পূজা।");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 130, 400, 230);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 260, 120, 120);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 390, 120, 120);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(100, 390, 120, 120);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(200, 390, 120, 120);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(300, 390, 120, 120);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANIK\\Documents\\NetBeansProjects\\DurgaPuja2016\\durga.png")); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(400, 390, 120, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Saptami.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Saptami.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Saptami.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Saptami.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Saptami().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
