/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hellokiddy;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author ANIK
 */
public class FirstFrame extends javax.swing.JFrame {

    /**
     * Creates new form firstFrame
     */
    public FirstFrame() {
        initComponents();
    }
    
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        flowerButton = new javax.swing.JButton();
        fruitButton = new javax.swing.JButton();
        birdsButton = new javax.swing.JButton();
        animalsButton = new javax.swing.JButton();
        firstLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 485));
        setResizable(false);
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(177, 227, 242));
        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jTextField1.setText("    HELLO KIDDY");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 20, 200, 60);

        flowerButton.setBackground(new java.awt.Color(204, 255, 255));
        flowerButton.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        flowerButton.setText("FLOWERS");
        flowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flowerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(flowerButton);
        flowerButton.setBounds(350, 150, 100, 30);

        fruitButton.setBackground(new java.awt.Color(204, 255, 255));
        fruitButton.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        fruitButton.setText("FRUITS");
        fruitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(fruitButton);
        fruitButton.setBounds(350, 200, 100, 30);

        birdsButton.setBackground(new java.awt.Color(204, 255, 255));
        birdsButton.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        birdsButton.setText("BIRDS");
        birdsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birdsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(birdsButton);
        birdsButton.setBounds(350, 250, 100, 30);

        animalsButton.setBackground(new java.awt.Color(204, 255, 255));
        animalsButton.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        animalsButton.setText("ANIMALS");
        animalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(animalsButton);
        animalsButton.setBounds(350, 300, 100, 30);

        firstLabel.setIcon(new javax.swing.ImageIcon("E:\\JavaPrograms\\NetBeans_Projects\\HelloKiddy\\src\\background\\animal-jungle-eps-file-simple-gradients-no-effects-no-mesh-no-transparencies-all-separate-layer-group-easy-38934923.jpg")); // NOI18N
        getContentPane().add(firstLabel);
        firstLabel.setBounds(0, 0, 700, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void flowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flowerButtonActionPerformed
        close();
        FirstFrame frame = new FirstFrame();
        frame.setVisible(false);
        FlowerFrame flower = new FlowerFrame();
        flower.setVisible(true);
    }//GEN-LAST:event_flowerButtonActionPerformed

    private void fruitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitButtonActionPerformed
        close();
        FirstFrame frame = new FirstFrame();
        frame.setVisible(false);
        FruitFrame fruit = new FruitFrame();
        fruit.setVisible(true);
    }//GEN-LAST:event_fruitButtonActionPerformed

    private void birdsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birdsButtonActionPerformed
        close();
        FirstFrame frame = new FirstFrame();
        frame.setVisible(false);
        BirdFrame bird = new BirdFrame();
        bird.setVisible(true);
    }//GEN-LAST:event_birdsButtonActionPerformed

    private void animalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalsButtonActionPerformed
        close();
        FirstFrame frame = new FirstFrame();
        frame.setVisible(false);
        AnimalFrame animal = new AnimalFrame();
        animal.setVisible(true);
    }//GEN-LAST:event_animalsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FirstFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton animalsButton;
    private javax.swing.JButton birdsButton;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JButton flowerButton;
    private javax.swing.JButton fruitButton;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
